service: hms-email-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
    host: 0.0.0.0

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true